routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get("stars/{star}", "StarController@show")->name("stars.show");
Route::get('/{star?}',"StarController@show")->name("home")->where('star', '[0-9]+');


Route::group(["middleware"=>["auth"], "prefix"=>"dashboard"], function (){
    Route::resource("stars", "StarController")->except("show");
    Route::post("stars/suppressions", "StarController@multipleSuppression")->name("stars.multipleSuppression");
});

app/Star.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Star extends Model
{
    //
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'prenom', 'nom', 'image', 'description', 'naissance',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'naissance' => 'datetime',
    ];

    public static $rules = [
        'nom' => 'required',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StarController.php
<?php

namespace App\Http\Controllers;

use App\Star;
use Illuminate\Http\Request;

use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Validator;

class StarController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stars = Star::all();
        return view("stars.index", compact("stars"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view("stars.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validation des règles 
        $rules = Star::$rules;
        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->back()->with("error", "Le champ nom est obligatoire.".json_encode($validator->failed()));
        }

        // Création du profil
        $star = Star::create($request->all());

        // Mise à jour de l'image du profil 
        if($request->file("image")){
            $path = $request->file("image")->store("images", "public");
            $star->image = $path;
        }
        $star->save();

        return redirect()->route("stars.index")->with("success", "Le profil a bien été créé.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Star  $star
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Star $star)
    {
        $stars = Star::paginate(100);
        return view("welcome", compact("stars", "star"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Star  $star
     * @return \Illuminate\Http\Response
     */
    public function edit(Star $star)
    {
        return view("stars.edit", compact("star"));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Star  $star
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Star $star)
    {
        // 
        $rules = Star::$rules;
        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->back()->with("error", "Le champ nom est obligatoire.".json_encode($validator->failed()));
        }

        if($request->file("image")){
            $path = $request->file("image")->store("images", "public");
            $star->image = $path;
        }
        $star->nom = $request->nom;
        $star->prenom = $request->prenom;
        $star->description = $request->description;
        $star->naissance = $request->naissance;
        $star->save();
        return redirect()->route("stars.index")->with("success", "Le profil a bien été modifié.");
    }

    /**
     * Supprime une star précise.
     *
     * @param  \App\Star  $star
     * @return \Illuminate\Http\Response
     */
    public function destroy(Star $star)
    {
        $star->delete();
        return redirect()->route("stars.index")->with('success', "Le profil a été supprimé avec succès");
    }

     /**
     * Supprime une liste de profils à partir de leur ID.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function multipleSuppression(Request $request)
    {
        if($request->ids){
            $ids = $request->ids;
            foreach ($ids as $id) {
                $star = Star::find($id);
                $star->delete();
            }
            $message = sizeof($ids).' profil(s) supprimé(s) avec succès';
            $type = "success";
        }
        else{
            $type = "warning";
            $message = "Aucun profil n'a été supprimé";
        }
        return redirect()->route("stars.index")->with($type, $message);
    }
}

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Browser - Administration</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset("css/icons/font-awesome/css/fontawesome-all.css")}}">
    <link rel="stylesheet" href="{{asset("css/icons/themify-icons/themify-icons.css")}}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
    @yield('css')
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{route("home")}}">Profile Browser</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav ml-auto">
                    {{-- <li class="nav-item">
                        <a class="nav-link" href="{{route("home")}}">Accueil</a>
                    </li> --}}
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <span class="ml-2 d-none d-lg-inline-block"><span>Salut,</span> <span>{{Auth::user()->name}}</span> <i data-feather="chevron-down"
                                    class="svg-icon"></i></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                           
                            <a class="dropdown-item" href="#!" onclick="document.logout.submit()"><i
                                    data-feather="power" class="svg-icon mr-2 ml-1"></i>
                                Déconnexion</a>
                            <form action="{{route("logout")}}" method="post" name="logout">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section>
        <div class="container">
            <div class="row mt-5 mb-5">
                <div class="col-12">
                    @include("layouts.successError")
                    @yield("content")
                </div>
            </div>
        </div>
    </section>
    @yield('scripts')
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Connexion') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Inscription') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/successError.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong><?php echo $message ?></strong>
</div>
@endif


@if (count($errors)>0)
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
    <ul>
        @foreach($errors->all() as $error)
            <li><?php echo $error ?></li>
        @endforeach
    </ul>
</div>
@endif

@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
    <strong><?php echo $message ?></strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong><?php echo $message ?></strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong><?php echo $message ?></strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	Please check the form below for errors
</div>
@endif

resources/views/stars/create.blade.php
@extends('layouts.admin')


{{-- Code CSS supplémentaire (soit des <link></link> soit <style></style>) --}}
@section('css')
<style>
    .file {
        visibility: hidden;
        position: absolute;
    }
</style>
@endsection

{{-- Code HTML --}}
@section('content')
<h4>Création d'un nouveau profil</h4>
<br>
<div class="card">
    <div class="card-body">
        <form action="{{route("stars.store")}}" class="row" enctype="multipart/form-data" method="post">
            @csrf
            <div class="col-sm-3">
                <div class="form-group">
                    <img src="{{asset("images/280x280.png")}}" style="width: 100%;" id="preview" class="img-thumbnail">
                </div>
                <div class="form-group">
                    <input type="file" name="image" class="file">
                    <div class="input-group my-3">
                        <input type="text" class="form-control custom-file-input" disabled
                            placeholder="Image de la star" id="file">
                        <div class="input-group-append">
                            <button type="button" class="browse btn btn-primary">Changer...</button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-sm-9">
                <div class="mT-30">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6 form-col">
                                <label for="prenom">Prénom </label>
                                <input type="text" name="prenom" class="form-control" id="prenom" placeholder="Prénom'">
                            </div>
                            <div class="col-sm-6 form-col">
                                <label for="nom">Nom*</label>
                                <input type="text" name="nom" class="form-control" id="nom" placeholder="Nom" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-12 form-col">
                                <label for="datetime">Date de naissance</label>
                                <input type="date" name="naissance" class="form-control" id="naissance">
                            </div>
                        </div>
                    </div>
                  
                    <div class="form-group">
                        <label for="description">Description </label>
                        <textarea name="description" cols="5" rows="5" class="form-control" id="description"
                            placeholder="Description de "></textarea>
                    </div>
                    <span class="small">(*) : Champs obligatoires</span>
                    <div class="text-right">
                        <a href="{{route("stars.index")}}" class="btn btn-secondary">Annuler</a>
                        <button type="submit" class="btn btn-success">Enregistrer</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

{{-- Code Scripts avec des balises <script></script> à ajouter--}}
@section('scripts')
<script>
    $(document).on("click", "#preview", function() {
    var file = $(this)
    .parent()
    .parent()
    .parent()
    .find(".file");
    file.trigger("click");
    });

    $(document).on("click", ".browse", function() {
    var file = $(this)
    .parent()
    .parent()
    .parent()
    .find(".file");
    file.trigger("click");
    });

    $('input[type="file"]').change(function(e) {
        var fileName = e.target.files[0].name;
        $("#file").val(fileName);
        
        var reader = new FileReader();
        reader.onload = function(e) {
            document.getElementById("preview").src = e.target.result;
        };
        reader.readAsDataURL(this.files[0]);
    });

</script>
@endsection

resources/views/stars/edit.blade.php
@extends('layouts.admin')


{{-- Code CSS supplémentaire (soit des <link></link> soit <style></style>) --}}
@section('css')
<style>
    .file {
        visibility: hidden;
        position: absolute;
    }
</style>
@endsection

{{-- Code HTML --}}
@section('content')
<h4>Modification du profil #{{$star->id}} : {{$star->prenom}} {{$star->nom}}</h4>
<br>
<div class="card">
    <div class="card-body">
        <form action="{{route("stars.update", $star)}}" class="row" enctype="multipart/form-data" method="post">
            @csrf
            @method("PUT")
            <div class="col-sm-3">
                <div class="form-group">
                    <img src="{{($star->image) ? (strpos($star->image, "https") !== false ? $star->image : asset('storage/'.$star->image)) : asset("images/280x280.png")}}" style="width: 100%;" id="preview" class="img-thumbnail">
                </div>
                
                <div class="form-group">
                    <input type="file" name="image" class="file">
                    <div class="input-group my-3">
                        <input type="text" class="form-control custom-file-input" disabled
                            placeholder="Image de la star" id="file">
                        <div class="input-group-append">
                            <button type="button" class="browse btn btn-primary">Changer...</button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-sm-9">
                <div class="mT-30">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6 form-col">
                                <label for="prenom">Prénom </label>
                            <input type="text" name="prenom" class="form-control" value="{{old("prenom") ? old("prenom") : $star->prenom}}" id="prenom" placeholder="Prénom'">
                            </div>
                            <div class="col-sm-6 form-col">
                                <label for="nom">Nom*</label>
                                <input type="text" name="nom" class="form-control"value="{{old("nom") ? old("nom") : $star->nom}}" id="nom" placeholder="Nom" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-12 form-col">
                                <label for="datetime">Date de naissance</label>
                                <input type="date" name="naissance" class="form-control" id="naissance" value="{{ isset($star->naissance) ? (new \DateTime($star->naissance))->format('Y-m-d'): ''}}">
                            </div>
                        </div>
                    </div>
                  
                    <div class="form-group">
                        <label for="description">Description </label>
                        <textarea name="description" cols="5" rows="5" class="form-control" id="description"
                            placeholder="Description de ">{{old("description") ? old("description") : $star->description}}</textarea>
                    </div>
                    <span class="small">(*) : Champs obligatoires</span>
                    <div class="text-right">
                        <a href="{{route("stars.index")}}" class="btn btn-secondary">Annuler</a>
                        <button type="submit" class="btn btn-success">Enregistrer</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

{{-- Code Scripts avec des balises <script></script> à ajouter--}}
@section('scripts')
<script>
    $(document).on("click", "#preview", function() {
    var file = $(this)
    .parent()
    .parent()
    .parent()
    .find(".file");
    file.trigger("click");
    });

    $(document).on("click", ".browse", function() {
    var file = $(this)
    .parent()
    .parent()
    .parent()
    .find(".file");
    file.trigger("click");
    });

    $('input[type="file"]').change(function(e) {
        var fileName = e.target.files[0].name;
        $("#file").val(fileName);
        
        var reader = new FileReader();
        reader.onload = function(e) {
            document.getElementById("preview").src = e.target.result;
        };
        reader.readAsDataURL(this.files[0]);
    });

</script>
@endsection

resources/views/stars/index.blade.php
@extends("layouts.admin")

{{-- Code CSS supplémentaire (soit des <link></link> soit <style></style>) --}}
@section('css')
<link href="{{asset("datatables.net-bs4/css/dataTables.bootstrap4.css")}}" rel="stylesheet">
@endsection

@section("content")
<div class="card">
    <div class="card-body">
        <div class="d-flex align-items-center mb-4">
            <h4 class="card-title">Profils enregistrés</h4>
            <div class="ml-auto">
                <a href="{{route("stars.create")}}" class="btn btn-primary btn-sm"> <span class="d-none d-sm-inline"> Ajouter un profil</span> <span class="d-inline d-sm-none"> <i class="ti-plus"></i> </span></a>
                @if($stars->count()>0)
                <a href="#!"
                    onclick="deleteAll()"
                    class="btn btn-danger btn-sm"><span class="d-none d-sm-inline">Supprimer la sélection</span><span class="d-inline d-sm-none"><i class="ti-trash"></i></span></a>
                @endif
            </div>
        </div>
        <hr>
        @if($stars->count()>0)
        <div class="table-responsive">
            <form action="{{route("stars.multipleSuppression")}}" method="post" name="deleteForm">
                @csrf
                <table id="dataTable" class="table table-striped table-bordered display no-wrap" cellspacing="0"
                    style="width: 100%">

                    <thead>
                        <tr>
                            <th>
                                <label class="custom-control custom-checkbox be-select-all">
                                    <input class="custom-control-input chk_all" type="checkbox" name="chk_all"><span
                                        class="custom-control-label"></span>
                                </label>
                            </th>
                            <th>Star </th>
                            <th>Dernière modif. </th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>
                              
                            </th>
                            <th>Star </th>
                            <th>Dernière modif. </th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($stars->reverse() as $star)
                        <tr>
                            <td class="px-2 py-4">
                                <label class="custom-control custom-checkbox">
                                    <input class="custom-control-input checkboxes" type="checkbox" value="{{$star->id}}"
                                        name="ids[]" id="check{{$star->id}}"><span class="custom-control-label"></span>
                                </label>
                            </td>
                            <td class="px-2 py-4">
                                <div class="d-flex no-block align-items-center">
                                    <div class="mr-3"><img
                                            src="@if($star->image == null) {{asset("images/280x280.png")}} @else {{(strpos($star->image, "https")=== false) ? asset('storage/'.$star->image) : $star->image}} @endif"
                                            alt="Photo de la star" class="rounded-circle" width="45" height="45" />
                                    </div>
                                    <div class="">
                                        <h5 class="text-dark mb-0 font-16 font-weight-medium">
                                            {{$star->prenom}} {{strtoupper($star->nom)}}
                                        </h5>
                                        <span class="text-muted font-14 text-truncate">Né(e) le {{$star->naissance->format("d/m/Y")}}</span>
                                    </div>
                                </div>
                            </td>


                            <td class="text-left">
                                {{$star->updated_at->diffForHumans()}}
                            </td>
                            <td class="text-left">
                                <div class="btn-group" role="group" aria-label="First group">
                                    </button>
                                    <a type="button" title="Afficher la page de la star" class="btn btn-success"
                                        href={{ route("stars.show", $star) }}><i class="ti-eye"></i></a>
                                    </a>
                                    <a type="button" title="Modifier la star" class="btn btn-warning"
                                        href={{ route("stars.edit", $star) }}><i class="ti-pencil "></i></a>
                                    </a>
                                    <button type="button" title="Supprimer la star"
                                        onclick="deleteProfile({{$star->id}})"
                                        class="btn btn-danger">
                                        <span class=""><i class="ti-trash"></i></span>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </form>
        </div>
        @else
        <div class="text-center">
            <h4 class="text-center">
                Aucune star n'a encore été ajoutée
            </h4>
            <img src="{{asset("images/empty.png")}}" class="img-fluid w-50" alt="Aucune star n'a encore été ajoutée"
                title="Aucune star n'a encore été ajoutée">
        </div>
        @endif
    </div>
</div>
@endsection

{{-- Code Scripts avec des balises <script></script> à ajouter--}}
@section('scripts')
<script src="{{asset("js/jquery.min.js")}}"></script>
<script src="{{asset("js/datatables/js/jquery.dataTables.min.js")}}"></script>
<script>
    $('#dataTable').DataTable({
        'paging' : true,
        'lengthChange': true,
        'searching' : true,
        'ordering' : true,
        'info' : true,
        'autoWidth' : true,
        fixedHeader: true,
        "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json"
        }
    })
    $(".checkboxes").click(function() {
        
        if ($(".checkboxes").length == $(".subscheked:checked").length) {
            $(".chk_all").attr("checked", "checked");
        } else {
            $(".chk_all").removeAttr("checked");
        }
        
    });

    $(".chk_all").click(function() {
        var checkAll = $(".chk_all").prop('checked');
        if (checkAll) {
            $(".checkboxes").prop("checked", true);
        } else {
            $(".checkboxes").prop("checked", false);
        }
        
    });

    function deleteProfile(id){
        if(confirm('Êtes-vous sûr de vouloir supprimer cette(s) star(s) ?')){
            document.querySelector('#check'+id).setAttribute('checked', 'checked');
            document.deleteForm.submit();
        }
    }

    function deleteAll(){
        if(confirm('Êtes-vous sûr de vouloir supprimer cette(s) star(s) ?')){
            document.deleteForm.submit();
        } 
    }
</script>
@endsection